Repository omroy07/AgriTech, pull requests merged in 2025-08, with the labels that each got.

#87 Add Google Sign-In to Login Form using Firebase Authentication
  firebase.js
  index.html
  login.css
  login.html
Labels: gssoc25, level2, Frontend

#91 Added feedback page with HTML, CSS, JS and updated main pages
  feed-back.css
  feed-back.html
  feed-back.js
  main.css
  main.html
Labels: gssoc25, level1, Frontend

#92 Add CODE_OF_CONDUCT for GSSoC'25 contribution
  CODE_OF_CONDUCT.md
Labels: documentation, gssoc25, level1

#88 Crop Prices Tracker
  Crop_Prices_Tracker/app.py
  Crop_Prices_Tracker/static/styles.css
  Crop_Prices_Tracker/templates/crop_price_tracker.html
  main.html
Labels: gssoc25, level2, AI

#114 Labour form validation
  Labour_Alerts/static/style.css
  Labour_Alerts/templates/labour.html
  farmer.css
  farmer.html
Labels: gssoc25, level1, Frontend

#123 Added a calendar for crops
  .vscode/settings.json
  croCalendar.js
  cropCalendar.css
  cropCalendar.html
  images/Calendar_Green_app_icon-removebg-preview.png
  main.css
  main.html
Labels: enhancement, gssoc25, level1, Frontend

#117 Integrated Gemini API for Smart Loan Eligibility Evaluation
  .gitignore.txt
  app.py
  script.js
  smart_loan.html
  style.css
Labels: enhancement, gssoc25, level1, AI

#128 PR #122 : Add Farmer Forum feature
  Forum/app.py
  Forum/forum.html
  Forum/forum.js
  main.html
Labels: enhancement, gssoc25, level1, Frontend

#129 Fix: Carousel loops back to first image after last (#120)
  images/AgriActImg1.jpeg
  images/AgriActImg2.jpeg
  images/AgriActImg3.jpeg
  index.html
  style.css
Labels: gssoc25, level1, Frontend

#158 Fix scroll-to-top arrow visibility on Home page
  index.html
  style.css
Labels: gssoc25, level1, Frontend

#177 Footer Section Update for All Pages
  Crop_Planning/templates/cropplan.html
  about.html
  chat.html
  cropCalendar.html
  disease.html
  farmer.html
  index.html
  main.html
  organic.html
  shopkeeper.html
  smart_loan.html
Labels: GSSoC25, level1, Frontend

#192 Fixed password toggle eye placement
  login.css
  register.css
Labels: GSSoC25, level1, Frontend

#218 login page password button is fixed
  login.css
Labels: GSSoC25, level1, Frontend

#219 Feedback form Redesign
  feed-back.css
  feed-back.html
Labels: GSSoC25, level2, Frontend

#225 Advanced Search, Filters & Responsive Dealer Listing UI
  shopkeeper.css
  shopkeeper.html
  shopkeeper.js
Labels: GSSoC25, level2, Frontend

#224 Fixed the overlaping buttons on the calender page
  cropCalendar.css
Labels: GSSoC25, level1, Frontend

#227 Updated ui of feedback form , footer of dashboard and solved login issue
  feed-back.css
  feed-back.html
  index.html
  main.css
  main.html
Labels: GSSoC25, level1, Frontend

#226 Enhanced card selection visibility in farmer dashboard
  main.css
Labels: GSSoC25, level1, Frontend

#228 Made Dark/Light Themes visible on all cards
  Crop Recommendation/templates/index.html
  Crop Yield Prediction/crop_yield_app/templates/index.html
  Crop_Planning/static/style.css
  Crop_Planning/templates/cropplan.html
  Crop_Prices_Tracker/templates/crop_price_tracker.html
  Forum/forum.html
  disease.css
  disease.html
  farmer.html
  organic.html
  theme.css
Labels: GSSoC25, level1, Frontend
