Repository omroy07/AgriTech, pull requests merged in 2025-09, with the labels that each got.

#235 Pull Request of Fertilizer Recommendation System using Machine Learning
  Fertiliser Recommendation System/README.md
  Fertiliser Recommendation System/assets/1.jpeg
  Fertiliser Recommendation System/assets/2.jpeg
  Fertiliser Recommendation System/assets/image.png
  Fertiliser Recommendation System/data/fertilizer_dataset.csv
  Fertiliser Recommendation System/requirements.txt
  Fertiliser Recommendation System/src/model.py
  Fertiliser Recommendation System/src/predict.py
  Fertiliser Recommendation System/src/train.py
  Fertiliser Recommendation System/src/utils.py
Labels: enhancement, GSSoC25, level2, ML, Frontend

#248 Update logo i cropplan.html
  Crop_Planning/templates/cropplan.html
Labels: GSSoC25, level1, Frontend

#253 Fixed the back button bug
  chat.css
  chat.html
Labels: bug, enhancement, GSSoC25, level2, Frontend

#241 Add dark mode support and improve UI styling
  main.css
  main.html
Labels: enhancement, GSSoC25, level1, Frontend

#240 Pull Request : Automated Plant Seedlings Classification with CNN Arch…
  Plant Seedlings Classification/Dataset/README.md
  Plant Seedlings Classification/Images/Screenshot 2025-09-02 130327.png
  Plant Seedlings Classification/Images/confusion matrix.png
  Plant Seedlings Classification/Images/plant1.jpg
  Plant Seedlings Classification/Images/plant2.png
  Plant Seedlings Classification/Model/Plant_seedlings_classification.ipynb
  Plant Seedlings Classification/README.md
  Plant Seedlings Classification/requirements.txt
Labels: enhancement, GSSoC25, level2, ML

#270 Pull Request : UI/UX Enhancement: About Us Page
  about.css
  about.html
Labels: gssoc25, level1

#258 Modified hover effects
  main.css
Labels: gssoc25

#263 Dark and Light Theme Issue resolved in yield prediction
  Crop Yield Prediction/crop_yield_app/templates/index.html
  main.css
  theme.js
Labels: gssoc25, level1, Frontend

#287 fixed planatation navbar text visibility
  plantation.css
Labels: gssoc25, level1, Frontend

#291 Add floating AI chatbot button on all pages
  about.css
  about.html
  cropCalendar.css
  cropCalendar.html
  disease.css
  disease.html
  farmer.css
  farmer.html
  index.html
  main.css
  main.html
  organic.css
  organic.html
  plantation.css
  plantation.html
  shopkeeper.css
  shopkeeper.html
  smart_loan.html
  style.css
  weather.css
  weather.html
Labels: gssoc25, level2, ML, Frontend, Backend

#292 Added search bar
  index.html
  main.html
  style.css
Labels: gssoc25

#312 Pull Request : Interactive Crop Calendar Enhancement
  cropCalendar.css
  cropCalendar.html
Labels: gssoc25, level2, Frontend

#324 feat: Redesign Smart Crop Recommender with modern UI and enhanced UX
  Crop Recommendation/templates/index.html
Labels: gssoc25, level3, Frontend, Backend

#335 Enhance Footer Layout and Mission Statement Display
  index.html
  style.css
Labels: gssoc25, level3

#330 ✨ Feature: Add Blog Section for Farming Tips & Updates (#310)
  blog.css
  blog.html
  blog.js
  index.html
Labels: gssoc25, level3

#325 Fix Back to Home Button Redirect in chat.html
  chat.html
Labels: gssoc25, level2

#323 Reorganize Project Directory
  .gitignore
  app.py
  cropCalendar.html
  disease.html
  farmer.html
  static/about.css
  static/auth.js
  static/chat.css
  static/chat.js
  static/croCalendar.js
  static/cropCalendar.css
  static/disease.css
  static/disease.js
  static/farmer.css
  static/farmer.js
  static/feed-back.css
  static/feed-back.js
  static/firebase.js
  static/login.css
  static/login.js
  static/main.css
  static/main.js
  static/organic.css
  static/organic.js
  static/plantation.css
  static/plantation.js
  static/register.css
  static/register.js
  static/script.js
  static/shopkeeper.css
  static/shopkeeper.js
  static/style.css
  static/terms-and-service.css
  static/theme.css
  static/theme.js
  static/weather.css
  static/weather.js
  templates/about.html
  templates/chat.html
  templates/cropCalendar.html
  templates/disease.html
  templates/farmer.html
  templates/feed-back.html
  templates/forgot-password.html
  templates/index.html
  templates/login.html
  templates/main.html
  templates/organic.html
  templates/plantation.html
  templates/register.html
  templates/shopkeeper.html
  templates/smart_loan.html
  templates/terms-and-service.html
  templates/weather.html
Labels: gssoc25, level2

#353 feat: Implement JSON chatbot with smart matching and mobile optimization
  chat.css
  chat.html
  chat.js
  chatbot-responses.json
  json-chatbot.js
Labels: gssoc25, level2, Frontend

#361 Adding new features government schemes page
  Gov_schemes/app_scheme.js
  Gov_schemes/index_scheme.html
  Gov_schemes/styles_scheme.css
  images/Scheme.jpg
  main.html
Labels: enhancement, gssoc25, level3, Frontend, Backend

#362 Fixes #351: Added Services Section
  crop.html
  financial-support.html
  index.html
  marketplace.html
  supply-chain.html
  sustainable-farming.html
Labels: gssoc25, level2

#370 Add files via upload
  Community/app.py
  Community/static/chat.js
  Community/static/style.css
  Community/tempCodeRunnerFile.py
  Community/templates/index.html
Labels: gssoc25, level1, level2, level3
